app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/	
Route::get('/', 'HomeController@index');



Auth::routes();

Route::resource('books', 'BookController');
Route::resource('orders', 'OrderController');
Route::resource('branches', 'BranchController');
Route::resource('users',  'UserController');

//cart route
Route::post('cart', 'OrderController@addToCart')->name('cart.add');
Route::delete('cart', 'OrderController@clearCart')->name('cart.clear');
Route::get('cart', 'OrderController@checkout')->name('cart.checkout');
Route::get('cart/delete/{id}', 'OrderController@deleteLine')->name('cart.delete_line');
Route::get('cart/reservation', 'CheckoutController@info')->name('checkout.info');
Route::post('cart/reservation', 'CheckoutController@store')->name('checkout.store');
Route::get('cart/confirm', 'CheckoutController@confirm')->name('checkout.confirm');

// user routes
Route::get('/profile', 'UserController@profile')->name('profile')->middleware('auth');
Route::put('/profile', 'UserController@update')->name('profile.update')->middleware('auth');


//
Route::delete('orders/line/{id}/destroy', 'OrderController@destroyLine')->name('orders.line_destroy');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $fillable =[
    	'title',
    	'photo',
    	'description',
      'year',
      'publisher',
    	'netto_price',
    	'price',
    	'quantity'
    ];
    public function getFormattedPriceAttribute($value)
    {
       return number_format($this->price, 2);
    }
    public function getFormattedNetoPriceAttribute($value)
    {
       return number_format($this->netto_price, 2);
    }
    public function order_lines()
   {
     return $this->hasMany('App\OrderLine');
   }

   public function getWithoutVat()
   {
       return \App\Price::getWithoutVat($this->FormattedPrice);
   }

   public function getVat()
   {
       return $this->FormattedPrice - $this->getWithoutVat();
   }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use Illuminate\Http\Request;

class bookController extends Controller
{
    public function __construct() {
        $this->middleware('auth.admin')
             ->except(['index', 'show']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::all();
        return view('book.index', compact('books')); /**['books'=> $books] tas pats butu compact($books)*/
    }

    

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('book.form', compact('book'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->hasFile('photo')){
            $file = $request->file('photo');
            $file->store('public');
            $photo= $file->hashName();
            }

       Book::create([
            'title' => $request->get('title'),
            'year' => $request->get('year'),
            'publisher' => $request->get('publisher'),
            'photo' => $photo,
            'description' => $request->get('description'),
            'price' => $request->get('price'),
            'netto_price' => $request->get('netto_price'),
            'quantity' => $request->get('quantity'),
          ]);


        return redirect()->route('books.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\book  $book
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $book = Book::find($id);
        return view('book.show', compact('book'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(book $book)
    {
        return view('book.form', compact('book'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, book $book)
    {
           if ($request->hasFile('photo')){
            $file = $request->file('photo');
            $file->store('public');
            $book->photo = $file->hashName();
            }

           $book->title= $request->title;
            $book->year= $request->year;
           $book->description = $request->description;
           $book->price = $request->price;
           $book->netto_price = $request->netto_price;
           $book->quantity = $request->quantity;
           

           $book->update();

        return redirect()->route('books.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Book::find($id)->delete();
        return redirect()->route('books.index');

    }
}

resources/views/book/form.blade.php
@extends('layouts.app')


	@section('content')
		
		<h2>Edit your book</h2>

		@if(isset($book))
			{!! Form::model($book, [
			'route' => ['books.update', $book->id],
			'method' => 'put',
			'files' => true
			]) !!}
		@else
			{!! Form::open(['route' => 'books.store', 'method' => 'post', 'files' => true]) !!}
		@endif
			
			<div class="from-group">    
			{!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Title'])!!}
			</div>
			
			<div class="from-group">  
			{!! Form::textarea('description', null, ['class' => 'form-control', 'placeholder' => 'Description']) !!}
			</div>
			
			
			
						
			<div class="from-group">  
			{!! Form::text('price', null, ['class' => 'form-control', 'placeholder' => 'Price']) !!}
			</div>

			<div class="from-group">  
			{!! Form::text('publisher', null, ['class' => 'form-control', 'placeholder' => 'Publisher']) !!}
			</div>

			<div class="from-group">  
			{!! Form::text('year', null, ['class' => 'form-control', 'placeholder' => 'Year']) !!}
			</div>

			<div class="from-group">  
			{!! Form::text('netto_price', null, ['class' => 'form-control', 'placeholder' => 'Netto Price']) !!}
			</div>
			
			<div class="from-group">  
			{!! Form::number('quantity', null, ['class' => 'form-control', 'placeholder' => 'Quantity']) !!}
			</div>


@if(isset($book) && $book->photo)
	<img class="book-form-photo" src="{{ asset('/storage/' . $book->photo)}}">
	@endif
			<div class="from-group">  
			{!! Form::file('photo', null, ['class' => 'form-control', 'placeholder' => 'IMAGE']) !!}

			</div>
	@if (Auth::check()) 

			{!! Form::submit('Save' ,['class' => 'btn-primary']) !!}
	
		@endif 	

		{!! Form::close() !!}



		@if(isset($book))
			{!! Form::open(['route' => ['books.destroy', $book->id], 'method' => 'delete'])!!}
				{!! Form::submit('Delete' , ['class' => 'btn btn-danger'])!!}
			{!! Form::close() !!}
		@endif

@endsection

resources/views/book/index.blade.php
@extends('layouts.app')

@section('content')

<h2>We Love Books...</h2>

@if(Auth::user() && Auth::user()->isAdmin())
<a href="{{route('books.create') }}" class="btn btn-warning" role="button">Add New Book to Menu</a> 
@endif		
<hr>
@foreach ($books->chunk(4)  as $chunk) 
<div class="row">
	@foreach ($chunk as $book)
	<div class="col-md-3"> 
		<div class="thumbnail">
			<img class="img-responsive book-cover" src="{{ asset('/storage/' . $book->photo)}}" >

			<div class="caption">
				<h3><i> {{ $book->title }}</i> </h3>
				<p><i> by:</i> <a href="#">{{ $book->publisher }}</a> </p>
				<p> {{ mb_strimwidth($book->description, 0 , 80, "...")  }} </p>
				<p>
					<strong>Year published:</strong>
					<i>{{ $book->year }} 
					</i></p>
					<p>
					<strong>Price:</strong>
					<i>{{ $book->FormattedPrice }} 
					EUR</i>
					@if(Auth::user() && Auth::user()->isAdmin())
					<strong>Netto :</strong>
					<i>{{ $book->FormattedNetoPrice }}</i>
					<strong>EUR</strong>
					@endif</p>
					<br>
					<p>
					<strong>Quantity:</strong>
					<i>{{ $book->quantity }} 
					pcs.</i>
				</p>
				<p>
					<a href="{{route('books.show', $book->id) }}" class="btn btn-primary" role="button">Show more</a>
					<a href="#" class="btn btn-warning add-to-cart"  data-id="{{ $book->id }}" role="button">Add to cart</a>  
				</p>
			</div>			
		</div>
	</div>
	<br>
	@endforeach	
</div>
@endforeach	
@endsection

resources/views/book/show.blade.php
@extends('layouts.app')

	@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<h2><i>{{ $book->title }}</i></h2>
				<p><i>by: </i><a href="">{{ $book->publisher }}</a></p>
				<hr>
				<div>
					<img src="{{ asset('/storage/' . $book->photo)}}">
				</div>
				<hr>
				<p>Story:</p>
				<p> {{ $book->description }}</p>
				<ul>
					<li>Price: <i>{{ $book->Formattedprice }} &euro;</i></li>
					<li>Books Left: <i> {{ $book->quantity }}pcs.</i></li>
					@if(Auth::user() && Auth::user()->isAdmin())
					<li>
					Netto :
					<i>{{ $book->FormattedNetoPrice }} 
					&euro;</i></li>
					@endif
					<li>Year published: <i>{{ $book->year }}</i></li>
				</ul>

				<a href="#" class="btn btn-warning add-to-cart"  data-id="{{ $book->id }}" role="button">Add to cart</a> 
			@if(Auth::user() && Auth::user()->isAdmin())
	   		 <a href="{{route('books.edit', $book->id) }}" class="btn btn-primary">EDIT</a>
			@endif 

		</div>

	</div>

	</div>

		
	@endsection