app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/	
Route::get('/', 'HomeController@index');



Auth::routes();

Route::resource('books', 'BookController');
Route::resource('orders', 'OrderController');
Route::resource('branches', 'BranchController');
Route::resource('users',  'UserController');

//cart route
Route::post('cart', 'OrderController@addToCart')->name('cart.add');
Route::delete('cart', 'OrderController@clearCart')->name('cart.clear');
Route::get('cart', 'OrderController@checkout')->name('cart.checkout');
Route::get('cart/delete/{id}', 'OrderController@deleteLine')->name('cart.delete_line');
Route::get('cart/reservation', 'CheckoutController@info')->name('checkout.info');
Route::post('cart/reservation', 'CheckoutController@store')->name('checkout.store');
Route::get('cart/confirm', 'CheckoutController@confirm')->name('checkout.confirm');

// user routes
Route::get('/profile', 'UserController@profile')->name('profile')->middleware('auth');
Route::put('/profile', 'UserController@update')->name('profile.update')->middleware('auth');


//
Route::delete('orders/line/{id}/destroy', 'OrderController@destroyLine')->name('orders.line_destroy');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'surname','email', 'password', 'dob', 'phone', 'address', 'city', 'zip', 'country'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    public function orders() {
        return $this->hasMany('App\Order');
    }

    /**
     * išrūšiuoja order'ius pagal kainą nuo didžiausios
     */
    public function getOrdersByPrice()
    {
        return $this->orders()->orderBy('total', 'desc')->get();
    }

    public function isAdmin()
    {
        return $this->type === 'admin';
    }

    public function getCountryName()
    {
        $countries = [
            'LT' => 'Lithuania'
        ];

        return isset($countries[$this->country]) ? $countries[$this->country] : $this->country;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function __construct () {
        $this->middleware('auth.admin')->except('profile', 'update');
    }

    public function index()
    {
        $users = User::all();
        return view('user.index', compact('users'));
    }

    public function profile()
    {
        $user = \Auth::user();
        $title = 'Update profile';
        return view('auth.register', compact('user', 'title'));
    }

    public function update(Request $request)
    {
        $user = \Auth::user();

        $user->name = $request->name;
        $user->surname = $request->surname;
        $user->dob = $request->dob;
        $user->phone = $request->phone;
        $user->city = $request->city;
        $user->zip = $request->zip;
        $user->country = $request->country;
        $user->save();

        return redirect()->route('books.index')->with('message', [
            'text' => 'Profile updated!',
            'type' => 'success'
        ]);
    }

    public function show(User $user)
    {
        return view('user.show', compact('user'));
    }
    public function destroy($id)
    {
        User::find($id)->delete();
        return redirect()->route('users.index');

    }
    
}

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<h1>List of users</h1>

	<table class="table table-hover">
		<thead>
			<tr>
				<td>#</td>
				<td>Name</td>
				<td>Type</td>
				<td>Email</td>
				<td>Orders</td>
				<td></td>
			</tr>
		</thead>
		<tbody>
		@foreach($users as $index => $user)
			<tr>
				<td>{{ $index + 1 }}</td>
				<td>{{ $user->name }}</td>
				<td><span class="badge">{{ $user->type }}</span></td>
				<td>{{ $user->email }}</td>
				<td>{{ count($user->orders) }}</td>
				<td><a href="{{ route('users.show', $user) }}">View</a></td>
				<td>
                            @if(isset($user))
                            {!! Form::open(['route' => ['users.destroy', $user->id], 'method' => 'delete'])!!}
                            {!! Form::submit('Delete' , ['class' => 'btn btn-danger'])!!}
                            {!! Form::close() !!}
                            @endif
                           </td>
				
			</tr>
		@endforeach
		</tbody>
	</table>
</div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<h1>User information</h1>

    <div class="row">
        <div class="col-md-6">
            <dl class="dl-horizontal">
              <dt>Name</dt>
              <dd>{{ $user->name }}</dd>
            </dl>
        </div>
        <div class="col-md-6">
            <dl class="dl-horizontal">
                <dt>Address</dt>
                <dd>{{ $user->address }}</dd>
                <dt>City</dt>
                <dd>{{ $user->city }}</dd>
                <dt>Country</dt>
                <dd>{{ $user->getCountryName() }}</dd>
            </dl>
        </div>
    </div>

    <div class="row">
        <h2>Orders</h2>
        <hr />
        <table id="table-with-sorting" class="table table-bordered">
            <thead>
                <tr>
                    <th>Order Id</th>
                    <th>Total price</th>
                    <th>Dishes count</th>
                    <th>Contact Name</th>
                    <th>Phone</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($user->getOrdersByPrice() as $order)
                    <tr class="{{ $order->getReservationClass() }}">
                        <td>#{{ $order->id }}</td>
                        <td>{{ $order->total }}€</td>
                        <td>{{ $order->order_lines->sum('quantity') }}</td>
                        <td>{{ $order->name }}</td>
                        <td>{{ $order->phone }}</td>
                        <td>
                            {!! Form::open(['route' => ['orders.destroy', $order->id], 'method' => 'delete'])!!}
                                <a href="{{ route('orders.show', $order) }}" class="btn btn-default"><span class="glyphicon glyphicon-eye-open"></span> Peržiūra</a>
								{!! Form::hidden('redirect_url', route('users.show', $user)) !!}
                				{!! Form::submit('Delete' , ['class' => 'btn btn-danger'])!!}
                			{!! Form::close() !!}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection