app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/	
Route::get('/', 'HomeController@index');



Auth::routes();

Route::resource('books', 'BookController');
Route::resource('orders', 'OrderController');
Route::resource('branches', 'BranchController');
Route::resource('users',  'UserController');

//cart route
Route::post('cart', 'OrderController@addToCart')->name('cart.add');
Route::delete('cart', 'OrderController@clearCart')->name('cart.clear');
Route::get('cart', 'OrderController@checkout')->name('cart.checkout');
Route::get('cart/delete/{id}', 'OrderController@deleteLine')->name('cart.delete_line');
Route::get('cart/reservation', 'CheckoutController@info')->name('checkout.info');
Route::post('cart/reservation', 'CheckoutController@store')->name('checkout.store');
Route::get('cart/confirm', 'CheckoutController@confirm')->name('checkout.confirm');

// user routes
Route::get('/profile', 'UserController@profile')->name('profile')->middleware('auth');
Route::put('/profile', 'UserController@update')->name('profile.update')->middleware('auth');


//
Route::delete('orders/line/{id}/destroy', 'OrderController@destroyLine')->name('orders.line_destroy');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Order extends Model
{
  protected $fillable =[
  'name',
  'email',
  'total',
  'date',
  'user_id',
  'reservation_date',
  
  'branch_id',
  
  'contact_phone'
  
  ];

  public function order_lines()
  {
   return $this->hasMany('App\OrderLine');
 }
 public function user()
 {
  return $this->belongsTo('App\User');
}

public function branch()
{
 return $this->belongsTo('App\Branch');
}

public function getReservationClass() : string
{
 /* šviesaforą rodome tik tada, kai žiūri administratorius */
 if (\Auth::check() && \Auth::user()->isAdmin()) {
   $date = Carbon::parse($this->reservation_date);

   if ($date->isToday()) {
     return 'danger';
   } else if ($date->isTomorrow()) {
     return 'info';
   } else if ($date->isPast()) {
     return 'success';
   }
 }

 return '';
}

public function getWithoutVat()
  {
   return \App\Price::getWithoutVat($this->total);
  }

public function getVat()
  {
   return $this->total - $this->getWithoutVat();
  }
  public function __toString(){
        return $this->title ;
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use App\Order;
use App\OrderLine;
use App\Branch;
use Illuminate\Http\Request;
use App\Price;

class OrderController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth.admin')
        ->except(['index', 'show', 'store' , 'addToCart', 'clearCart', 'deleteLine', 'checkout']);

        $this->middleware('auth')
        ->except(['addToCart', 'clearCart', 'deleteLine', 'checkout']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (\Auth::user()->isAdmin()) {
            $orders = Order::all();
        } else {
            // $orders = Order::where('user_id', \Auth::user()->id)->get();
            $orders = \Auth::user()->orders;
        }

        return view('order.index', ['orders'=> $orders]);
    }
//


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
     if (session('cart.total')){
        return view('order.form');
    } else {
        return redirect()->route('books.index');
    }

}

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $order = Order::create([
            'name' => session('cart.reservation_info.name'),
            'email' => \Auth::user()->email,
            'total' => session('cart.total'),
            'date' => \Carbon\Carbon::now(),
            'user_id' => \Auth::user()->id,
            'contact_phone' =>  session('cart.reservation_info.phone'),
            'reservation_date' => session('cart.reservation_info.date'),            
            'branch_id' => session('cart.reservation_info.branch_id')
            ]);

        foreach(session('cart.items') as $item) {
            OrderLine::create([
                'order_id' => $order->id,
                'book_id' => $item['id'],
                'quantity' => $item['quantity'],
                'total' => $item['total']
                ]);
        }
        $this-> clearCart();
        return redirect()->route('branches.index')->with('message', [
            'text' => 'Your order was placed successfully!',
            'type' => 'success'
            ]
            );
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order::find($id);
        $branches = Branch::all()->pluck('name');
        $address = Branch::all()->pluck('address');
        return view('order.show', compact('order', 'branches', 'address'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $books = Book::all()->pluck('title', 'id');
        $order = Order::find($id);
        $branches = Branch::all()->pluck('name', 'id');
        
        return view('order.form', compact('order', 'books', 'branches'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,order  $order)
    {
        
        


        $order->name= $request->name;
        $order->email = $request->email;
        
        $order->contact_phone = $request->phone;
        $order->date = \Carbon\Carbon::now();
        $order->reservation_date = $request->reservation_date;
          
          $order->update();
        return redirect()->route('orders.index');

    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */


    public function destroy(Order $order, Request $request)
    {
        $order->order_lines()->delete();
        $order->delete();

        if ($request->has('redirect_url')) {
            return redirect()->to($request->redirect_url);
        }

        return redirect()->route('orders.index');
    }

    public function addToCart(Request $request){
        // session(['cart.items'=> [] ]);
        $book_id = $request->id;

        $book = Book::find($book_id);
        $product = [
        'id' => $book->id,
        'photo' => $book->photo,
        'title' => $book->title,
        'quantity' => 1,
        'price' => $book->FormattedPrice,
        'total' =>$book->FormattedPrice,
        'without_vat' => $book->getWithoutVat(),
        'vat' => $book->getVat()
        ];
        $items = session('cart.items');
        $existing = false;
        $grand_total = 0;

        if ($items && count($items) > 0) {

            foreach($items as $index => $item) {
                if($item['id'] == $book_id) {
                    $items[$index]['quantity'] = $item['quantity'] + $product['quantity'];
                    $items[$index]['total'] = $items[$index]['quantity'] * $book->FormattedPrice;
                    $items[$index]['without_vat'] = $items[$index]['quantity'] * $book->getWithoutVat();
                    $items[$index]['vat'] = $items[$index]['quantity'] * $book->getVat();
                    $existing = true;
                    
                } 
            }
        }
        if(! $existing){
            session()->push('cart.items', $product);
            $grand_total += $product['total'];
        } else {
            session(['cart.items'=> $items]);
        }


        $this->calculateCartTotals();
        return session('cart');
    }

    public function clearCart() {
        session(['cart.items' => [],  'cart.total' =>0]);

    }   
    

    public function deleteLine(Request $request) {
        $id = $request->id;
        $items = session('cart.items');

        $total = session('cart.total');

        foreach ($items as $index => $item) {
            if ($item['id'] == $id) {
                $total -= $item['total'];
                unset($items[$index]);
                break;
            }
        }

        session([

            'cart.items' => $items,
            
            ]);
        $this->calculateCartTotals();

        return redirect()->route('cart.checkout');
    }
    private function calculateCartTotals() {
        $items = session('cart.items');
        $grand_total = 0;

        foreach($items as $item) {
            $grand_total = $grand_total + $item['total'];
        }


        $withoutVat = Price::getWithoutVat($grand_total);
        $vat = Price::getVat($grand_total);

        session([
            'cart.total_without_vat' => $withoutVat,
            'cart.total_vat' => $vat,
            'cart.total' => $grand_total
            ]);

    }


    public function checkout()
    {
        return view('order.checkout');
    }

    public function destroyLine($id) {
        $line= OrderLine::find($id);
        
        $line->order->total -= $line->total;
        $line->order->save();
        $line->delete();

        return redirect()->route('orders.edit', $line->order->id);
    }

    public function addToOrder($id, request $request){
        echo dd($request);

        $order =Order::find($id);
        $book=Book::find($request->book);
        $line = new \App\OrderLine();
        $line->order=$order;
        $line->quantity=$request->quantity;
        $line->book=$request->book;
        $line->total=$book->price * $request->quantity;


        echo dd($request);

        $line->save();

        return redirect()->route('orders.edit');

    }
}

resources/views/order/checkout.blade.php
@extends('layouts.app')

@section('content')

<div class="table-responsive">
  <table class="table">
@if(!session('cart.items'))

  <h2>Your cart is empty</h2>
  <hr>
   <a href="{{ route('books.index') }} " class="btn btn-success">Browse book shelf</a>

@else

<h2>Your cart</h2>
<hr>


	<tbody>
		<thead>
			<th>Name</th>
      <th>Price for One</th>
			<th>Quantity</th>
			<th>Total</th>
      <th>VAT</th>
      <th>All w/ VAT</th>
			<th>Clear</th>
		</thead>
	@if(session('cart.items') && count(session('cart.items'))>0)
        @foreach(session('cart.items') as $item)
            <tr>
                <td>{{ $item['title']}} <img src="{{ asset('/storage/' . $item['photo'])}}" alt="{{ $item['title']}}" class="img-rounded" style="width: 70px;"> </td>
                <td>{{ $item['price']}} €</td>
                <td>{{ $item['quantity']}} </td>
                <td>{{ $item['total']}} €</td>
                <td>{{ $item['vat'] }}€</td>
                <td>{{ $item['without_vat'] }}€</td>

               <td><a class="clear-line-cart" href="{{ route('cart.delete_line', ['id' => $item['id']] ) }}"><i class="fa fa-trash-o" aria-hidden="true">X</i></a></td>
             </tr>

            @endforeach
            <tfoot>
            	<td></td>
            	<td></td>
            	<td>In total : </td>
              <td> {{session('cart.total') ?: '0'}} &euro;</td>
            	
              <td>{{ session('cart.total_vat') ?: '0' }} €</td>
              <td>{{ session('cart.total_without_vat') ?: '0' }} &euro;</td>
              
            </tfoot>
        

@endif
	</tbody>

  </table>
@if(Auth::check())
<a href="{{route('checkout.info') }}" class="btn btn-success">Continue</a>
@else
   <a href="{{ route('register') }}" class="btn btn-success">Continue and Register</a>
@endif
@if(session('cart.items') && count(session('cart.items'))==0)

 
  @endif

</div>
@endif

@endsection

resources/views/order/form.blade.php
@extends('layouts.app')


@section('content')

<h2>Order edit:</h2>
<hr>

@if(isset($order))
{!! Form::model($order, [
	'route' => ['orders.update', $order->id], 'method' => 'put'
	]) !!}
	@else
	{!! Form::open(['route' => 'orders.store', 'method' => 'post']) !!}
	@endif

	<div class="from-group">
	{!! Form::label('name', 'Name') !!}    
		{!! Form::text('name', Auth::user() ? Auth::user()->name: null, ['class' => 'form-control', 'placeholder' => 'Name'])!!}
	</div>
	<div class="from-group">  
	{!! Form::label('email', 'Email') !!}  
		{!! Form::text('email', Auth::user() ? Auth::user()->email: null, ['class' => 'form-control', 'placeholder' => 'Email'])!!}
	</div>
	<div class="from-group">
	{!! Form::label('phone', 'Phone No.') !!}    
		{!! Form::text('phone', Auth::user() ? Auth::user()->phone: null, ['class' => 'form-control', 'placeholder' => 'Phone'])!!}
	</div>
	<div class="from-group"> 
	{!! Form::label('reservation_date', 'Date of collection') !!}
	  {!! Form::date('reservation_date', Auth::user() ? Auth::user()->date : null, ['class' => 'form-control', 'placeholder' => 'Date']) !!}
	  </div>
	
<br>
@if (Auth::check()) 

{!! Form::submit('Save' ,['class' => ' btn btn-warning']) !!}
{!! Form::close() !!}
@endif 	
<br>

@if(count($order->order_lines))
<table class="table">
	<tr>
		<th><i>Book</i></th>
		<th><i>Quantity</i></th>
		<th><i>Price</i></th>
		<th><i>Delete</i></th>
	</tr>

	@foreach($order->order_lines as $line)
		<tr>
			<td>{{ $line->book->title  }}</td>
			<td>{{ $line->book->quantity  }}</td>
			<td>{{ $line->book->price  }}</td>
			<td>{!! Form::open(['route' => ['orders.line_destroy', $line->id], 'method' => 'delete'])!!}
			{!! Form::submit('Delete' , ['class' => 'btn btn-danger'])!!}
{!! Form::close() !!}</td>
		</tr>

@endforeach
</table>
@endif
	

@endsection

resources/views/order/index.blade.php
@extends('layouts.app')

@section('content')

<h2>Order list :</h2>

		<hr>
			<div class="row">
				@foreach ($orders as $order)
					<div class="col-md-6 col-md-offset-3"> 
						<ul>
							<li><h3>Name: {{ ucfirst($order->name) }} </h3> <p>E-mail: {{ $order->email }} </p> <p>Order total:{{ $order->total }} Eur.</p> <p>Date ordered: {{ $order->date }}</p>
							<p>Collect Date: {{ $order->reservation_date }}</p>
							<p>no VAT: {{ $order->getWithoutVAT() }} &euro; <br>
							Order price: {{ $order->total }} &euro;</p>
							<p><a href="{{route('orders.show', $order->id) }}" class="btn btn-primary" role="button">Show Details</a></p>
							
							</li>
							<hr>
						</ul>

							
									 
					</div>
		 		@endforeach	
			
			</div>
 		<hr>
 		@if(Auth::user() && Auth::user()->isAdmin())
 		<a href="{{route('orders.create') }}" class="btn btn-primary" role="button">Make new Order</a> 
 		@endif	
@endsection

resources/views/order/show.blade.php
@extends('layouts.app')

	@section('content')
	<div class="container">
	<h2>Order details</h2>
	<hr>
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<ul>
					<li>Ordered by: {{ $order->name }} </li>
					<li>Contact E-mail: {{ $order->email }} </li>
					<li>Date ordered: {{ $order->date }} </li>
					<li>Collect date: {{ $order->reservation_date }} </li>
					<li>Pickup branch: {{  $order->branch_id = $branches[0] }} </li>
					<li>Branch address : {{  $order->branch_id = $address[0] }} </li>
				</ul>
				<table class="table">
						<thead>
							<th>Name</th>
							<th>Quantity</th>
							<th>Price</th>
							<th>Total</th>
							@if(Auth::user() && Auth::user()->isAdmin())
							<th>Delete</th>
							@endif
						</thead>
					@if(count($order->order_lines()) >0)
				       <tbody>
				        @foreach($order->order_lines as $item) 
				            <tr>         
				                <td>{{ $item->book->title }} <img src="{{ asset('/storage/' . $item->book->photo)}}" alt="{{ $item->book->title }}" class="img-rounded" style="width: 70px;"></td>
				                <td>{{ $item->quantity }} </td>
				                <td>{{ $item->book->price }} </td>
				                <td>{{ $item->total }} </td>
				                @if(Auth::user() && Auth::user()->isAdmin())
				                <td><a id="clear-line-cart" href="#" ><i class="fa fa-trash-o" aria-hidden="true"></i>X</a></td>
				                @endif
				            </tr>  
				        @endforeach
				        </tbody>
				        <tfoot>
			            	<tr>
			            		<td colspan="3" class="text-right">Total:</td>
			            		<td>{{ $order->total }}</td>
			            	</tr>
				        </tfoot>  
				    @endif
				</table>
   				
					@if(Auth::user() && Auth::user()->isAdmin())
	   		 <a href="{{route('orders.edit', $order->id) }}" class="btn btn-primary">Edit order</a>
			@endif 
			</div>
		</div>
	</div>
	@endsection